#!/bin/sh


for transform in $*; do
	for narms in 8 16 32 64 128 ; do
		nsamples=`python -c "import math; print int(round(10000/math.log($narms)*math.log(2)))"`
		echo $narms $nsamples $transform
		./runrexp $narms  $nsamples $transform
	done
done

